### Collection-data

In [19]:
import chromadb

client = chromadb.PersistentClient(path="db_openai") #db_openai, db_gemini
col = client.get_collection(name="cosmetics_kb_openai")#cosmetics_kb_openai"), cosmetics_kb_gemini
N = 5

# ids include listesine konmaz. ids zaten döner.
data = col.get(include=["documents", "metadatas"], limit=N)

#data.keys()
#data["metadatas"][0]["brand"]
#data["documents"][0]
#col.get()
data

Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given
Failed to send telemetry event CollectionGetEvent: capture() takes 1 positional argument but 3 were given

{'ids': ['02415a33943b2cc65c009174fd5b3f5a0cffb6f23d553fd8266e9b7f26f16cc0',
  '0298e1a8255f33f4ad3cdddc06c0436c6d97e78894df11e4e25b28252d3143dd',
  '1ed4a690fab7fbe6a3af924503e394f4f2ee9163677f565770bc5854c289d1f7',
  '20ce764b52496eeafeb50b1be4dcf0e77464a0795fe242ffa2f1d5b06723aa92',
  '4b5f8dccd311e47730367e5f87026a831d17eef1e65d4ab7be67cbac5c0b3d84'],
 'embeddings': None,
 'metadatas': [{'brand': 'IT COSMETICS',
   'label': 'Moisturizer',
   'name': 'Your Skin But Better™ CC+™ Cream with SPF 50+',
   'price': 38.0,
   'product_id': '02415a33943b2cc65c009174fd5b3f5a0cffb6f23d553fd8266e9b7f26f16cc0',
   'rank': 4.1},
  {'brand': 'DRUNK ELEPHANT',
   'label': 'Moisturizer',
   'name': 'Virgin Marula Luxury Facial Oil',
   'price': 72.0,
   'product_id': '0298e1a8255f33f4ad3cdddc06c0436c6d97e78894df11e4e25b28252d3143dd',
   'rank': 4.4},
  {'brand': 'TATCHA',
   'label': 'Moisturizer',
   'name': 'The Water Cream',
   'price': 68.0,
   'product_id': '1ed4a690fab7fbe6a3af924503e394f4f2ee9163677f565770bc5854c289d1f7',
   'rank': 4.2},
  {'brand': 'FARMACY',
   'label': 'Moisturizer',
   'name': 'Honeymoon Glow AHA Resurfacing Night Serum with Echinacea GreenEnvy™',
   'price': 58.0,
   'product_id': '20ce764b52496eeafeb50b1be4dcf0e77464a0795fe242ffa2f1d5b06723aa92',
   'rank': 4.6},
  {'brand': 'SHISEIDO',
   'label': 'Moisturizer',
   'name': 'Bio-Performance Advanced Super Revitalizing Cream',
   'price': 78.0,
   'product_id': '4b5f8dccd311e47730367e5f87026a831d17eef1e65d4ab7be67cbac5c0b3d84',
   'rank': 4.6}],
 'documents': ['Ürün adı: Your Skin But Better™ CC+™ Cream with SPF 50+\nMarka: IT COSMETICS\nKategori: Moisturizer\nFiyat: 38\nPuan: 4.1\nUygun cilt tipleri: Combination, Dry, Normal, Oily, Sensitive\n\nÜrün tanıtımı: Bu CC krem, cildinizi nemlendirirken renk eşitsizliklerini gidermeye ve yüksek SPF ile güneşten korumaya yardımcı olabilir. Cildinize daha iyi bir görünüm kazandırmayı hedefler.\nİçerik analizi: Ürün, nemlendirici, antioksidan ve yatıştırıcı özellikler sunan zengin bitki özleri, vitaminler ve peptitler içeren kompleks bir formüle sahiptir. Silikonlar ve SPF bileşenleri de mevcuttur. Stearik Asit, Orbignya Oleifera Seed Oil gibi bazı yağlar komedojenik risk taşıyabilir. Limon, bergamot, portakal gibi çeşitli narenciye ve okaliptüs yağları hassasiyet/iritasyon riski yaratabilir. Diğer riskler belirlenemedi.\n\nIngredients: Water, Snail Secretion Filtrate, Phenyl Trimethicone, Dimethicone, Butylene Glycol, Butylene Glycol Dicaprylate/Dicaprate, Orbignya Oleifera Seed Oil, Butyloctyl Salicylate, Cetyl Peg/Ppg-10/1 Dimethicone, Cyclopentasiloxane, Cyclohexasiloxane, Magnesium Sulfate, Polyglyceryl-4 Isostearate, Dimethicone/Vinyl Dimethicone Crosspolymer, Aluminum Hydroxide, Hexyl Laurate, Stearic Acid, Calcium Stearate, Caprylyl Glycol, Triethoxycaprylylsilane, Ethylhexylglycerin, Citrus Medica Limonum (Lemon) Peel Oil, Tocopheryl Acetate, Sorbitan Isostearate, Phenoxyethanol, Citrus Aurantium Bergamia (Bergamot) Fruit Oil, 1,2-Hexanediol, Disodium Edta, Citrus Aurantium Dulcis (Orange) Peel Oil, Citrus Aurantifolia (Lime) Oil, Vitis Vinifera (Grape) Seed Oil, Punica Granatum Seed Oil, Pinus Sylvestris Leaf Oil, Persea Gratissima (Avocado) Oil, Niacinamide, Citrus Grandis (Grapefruit) Peel Oil, Cholesterol, Anthemis Nobilis Flower Water, Lactobacillus/Honeysuckle Flower/Licorice Root/Morus Alba Root/Pueraria Lobata Root/Schizandra Chinensis Fruit/Scutellaria Baicalensis Root/Sophora Japonica Flower Extract Ferment Filtrate, Perfluorohexane, Olea Europaea (Olive) Leaf Extract, Glycerin, Eucalyptus Globulus Leaf Oil, Camellia Sinensis Leaf Extract, Chrysanthemum Indicum Flower Extract, Pueraria Lobata Root Extract, Perfluorodecalin, Morus Alba Fruit Extract, Magnolia Kobus Bark Extract, Glycine Soja (Soybean) Sprout Extract, Diospyros Kaki Leaf Extract, Cinnamomum Cassia Bark Extract, Artemisia Princeps Leaf Extract, Pentafluoropropane, Curcuma Longa (Turmeric) Root Extract, Steareth-20, Hydrolyzed Hyaluronic Acid, Colloidal Oatmeal, Hydrolyzed Silk, Citric Acid, Sodium Benzoate, Potassium Sorbate, Aloe Barbadensis Leaf Extract, N-Hydroxysuccinimide, Hydrolyzed Collagen, Caprylhydroxamic Acid, Tocopherol, Thiamine Hcl, Riboflavin, Retinyl Palmitate, Pantothenic Acid, Palmitoyl Oligopeptide, Niacin, Folic Acid, Chrysin, Carnitine Hcl, Biotin, Ascorbic Acid, Palmitoyl Tetrapeptide-7, Chlorhexidine Digluconate. May Contain: Iron Oxides (Ci 77492, Ci 77491, Ci 77499).\n',
  'Ürün adı: Virgin Marula Luxury Facial Oil\nMarka: DRUNK ELEPHANT\nKategori: Moisturizer\nFiyat: 72\nPuan: 4.4\nUygun cilt tipleri: Combination, Dry, Normal, Oily\n\nÜrün tanıtımı: Bu ürün, %100 saf Marula Çekirdeği Yağı içeren lüks bir yüz yağıdır. Cildi nemlendirmeye ve beslemeye yardımcı olabilir.\nİçerik analizi: Bu ürün, tek bir bileşen olan %100 saf Marula Çekirdeği Yağı içerir. Bu, formülün oldukça sade ve doğal olduğunu gösterir. Marula Çekirdeği Yağı, bazı cilt tiplerinde komedojenik risk taşıyabilir. Ayrıca, nadiren de olsa hassasiyet/iritasyon riski yaratabilir.\n\nIngredients: 100% Unrefined Sclerocraya Birrea (Marula) Kernel Oil.\n',
  'Ürün adı: The Water Cream\nMarka: TATCHA\nKategori: Moisturizer\nFiyat: 68\nPuan: 4.2\nUygun cilt tipleri: Combination, Normal, Oily, Sensitive\n\nÜrün tanıtımı: TATCHA The Water Cream, karma, normal, yağlı ve hassas cilt tipleri için tasarlanmış bir nemlendiricidir. Cilde hafif bir his sunmayı hedefleyebilir.\nİçerik analizi: Bu formül, su bazlı yapısı ve silikonlar ile hafif bir his sunarken, fermente içerikler ve çeşitli bitki özleri ile nemlendirme ve antioksidan destek sağlamayı hedefler. Komedojenik risk yaratabilecek içerikler arasında Dimethicone ve Butylene Glycol bulunabilir. Hassasiyet/iritasyon riski taşıyabilecek içerikler ise Parfum/Fragrance, Alcohol ve bazı bitki özleri olabilir.\n\nIngredients: Water, Saccharomyces/Camellia Sinensis Leaf/Cladosiphon Okamuranus/Rice Ferment Filtrate*, Dimethicone, Propanediol, Glycerin, Diglycerin, Diphenylsiloxy Phenyl Trimethicone, Gold, Belamcanda Chinensis Root Extract, Rosa Multiflora Fruit Extract, Houttuynia Cordata Extract, Sophora Angustifolia Root Extract, Sodium Hyaluronate, Lecithin, Pistacia Lentiscus (Mastic) Gum, Sodium Chloride, Sodium Citrate, Mica, Peg-9 Polydimethylsiloxyethyl Dimethicone, Dimethicone/Peg-10/15 Crosspolymer, Dimethicone/Phenyl Vinyl Dimethicone Crosspolymer, Disodium Edta, Tin Oxide, Titanium Dioxide, Butylene Glycol, Ethylhexylglycerin, Parfum/Fragrance, Alcohol, Phenoxyethanol. *Hadasei-3.\n',
  "Ürün adı: Honeymoon Glow AHA Resurfacing Night Serum with Echinacea GreenEnvy™\nMarka: FARMACY\nKategori: Moisturizer\nFiyat: 58\nPuan: 4.6\nUygun cilt tipleri: Combination, Dry, Normal, Oily, Sensitive\n\nÜrün tanıtımı: Bu gece serumu, AHA'lar ve çeşitli bitkisel özler ile cildin yenilenmesine yardımcı olmayı hedefleyebilir. Cilt tonu ve dokusunun iyileşmesine destek olabilir.\nİçerik analizi: Bu formül, AHA'lar (Laktik Asit, Glikolik Asit) ile güçlü bir eksfoliasyon sunarken, çeşitli bitki özleri ve nemlendiricilerle desteklenmiştir. Komedojenik risk taşıyabilecek içerikler arasında Cetearyl Alcohol, Polyglyceryl-10 Stearate olabilir. Hassasiyet/iritasyon riski yaratabilecek içerikler Laktik Asit, Glikolik Asit, Salix Alba (Willow) Bark Extract, Citrus Limon (Lemon) Fruit Extract ve Citral olabilir.\n\nIngredients: Water, Lactic Acid, Propanediol, Jojoba Esters, Glycolic Acid, Potassium Hydroxide, Salix Alba (Willow) Bark Extract, Carthamus Tinctorius (Safflower) Oleosomes, Vitis Vinifera (Grape) Seed Oil, Hibiscus Sabdariffa Flower Extract, Citric Acid, Honey Extract, Echinacea Purpurea Root Extract, Propolis Extract, Royal Jelly Extract, Hydrolyzed Sodium Hyaluronate, Hydrolyzed Hyaluronic Acid, Curcuma Longa (Turmeric) Root Extract, Argania Spinosa Kernel Oil, Zingiber Officinale (Ginger) Root Extract, Amaranthus Caudatus Seed Oil, Limnanthes Alba (Meadowfoam) Seed Oil, Vaccinium Myrtillus Fruit/Leaf Extract, Saccharum Officinarum (Sugarcane) Extract, Citrus Aurantium Dulcis (Orange) Fruit Extract, Citrus Limon (Lemon) Fruit Extract, Acer Saccharum (Sugar Maple) Extract, Melia Azadirachta Leaf Extract, Helianthus Annuus (Sunflower) Seed Oil, Melia Azadirachta Flower Extract, Salvia Hispanica Seed Oil, Cetearyl Alcohol, Glycerin, Arachidyl Alcohol, Sclerotium Gum, Coco-Glucoside, Polyacrylate Crosspolymer-6, Behenyl Alcohol, Arachidyl Glucoside, Sodium Benzoate, Tocopherol, Potassium Sorbate, Corallina Officinalis Extract, Polyglyceryl-10 Stearate, Gluconolactone, 1,2-Hexanediol, Ocimum Basilicum (Basil) Flower/Leaf Extract, Ocimum Sanctum Leaf Extract, T-Butyl Alcohol, Glucose, Calcium Gluconate, Citral.\n",
  'Ürün adı: Bio-Performance Advanced Super Revitalizing Cream\nMarka: SHISEIDO\nKategori: Moisturizer\nFiyat: 78\nPuan: 4.6\nUygun cilt tipleri: Belirlenemedi\n\nÜrün tanıtımı: Shiseido Bio-Performance Advanced Super Revitalizing Cream, cildin nemlendirilmesine ve canlanmasına yardımcı olmayı hedefleyen bir nemlendiricidir. Cilt görünümünü desteklemeye yönelik formüle edilmiştir.\nİçerik analizi: Bu formül nemlendirici ve yumuşatıcı bileşenler içerir. Antioksidanlar ve bazı aktif maddeler de bulunmaktadır. Cetyl Octanoate ve PEG-60 Hydrogenated Castor Oil komedojenik risk taşıyabilir. Parabenler, koku ve Octyl Methoxycinnamate hassasiyet/iritasyon riski yaratabilir.\n\nIngredients: Water, Glycerin, Cyclomethicone, Butylene Glycol, Dimethicone, Cetyl Octanoate, Squalane, Dimethicone Copolyol, Disteardimonium Hectorite, Hydrogenated C6-14 Olefin Polymers, PEG-150, Mortierella Oil, Phytosteryl Macadamiate, Tocopheryl Acetate, Stearyl Glycyrrhetinate, Arginine HCI, PEG-60 Hydrogenated Castor Oil, Sodium Glutamate, Disodium Adenosine Triphosphate, Saccharomyces Lysate Extract, Sodium Acetylated Hyaluronate, Rosa Roxburghii Extract, Octyl Methoxycinnamate, Agar, Sodium Hexametaphosphate, Trisodium EDTA, Tocopherol, BHT, Ethylparaben, Butylparaben, Methylparaben, Fragrance, Iron Oxides.\n'],
 'uris': None,
 'data': None,
 'included': ['documents', 'metadatas']}

### Excel

In [14]:
import pandas as pd
raw = pd.read_excel("data/uploads/cosmetics-data1.xlsx")
raw.head()

,Label,Brand,Name,Price,Rank,Ingredients,Combination,Dry,Normal,Oily,Sensitive
0,Moisturizer,LA MER,Crème de la Mer,175,4.1,"Algae (Seaweed) Extract, Mineral Oil, Petrolat...",1,1,1,1,1
1,Moisturizer,SK-II,Facial Treatment Essence,179,4.1,"Galactomyces Ferment Filtrate (Pitera), Butyle...",1,1,1,1,1
2,Moisturizer,DRUNK ELEPHANT,Protini™ Polypeptide Cream,68,4.4,"Water, Dicaprylyl Carbonate, Glycerin, Ceteary...",1,1,1,1,0
3,Moisturizer,LA MER,The Moisturizing Soft Cream,175,3.8,"Algae (Seaweed) Extract, Cyclopentasiloxane, P...",1,1,1,1,1
4,Moisturizer,IT COSMETICS,Your Skin But Better™ CC+™ Cream with SPF 50+,38,4.1,"Water, Snail Secretion Filtrate, Phenyl Trimet...",1,1,1,1,1

In [15]:
raw[raw["Name"] == "Crème de la Mer"]

,Label,Brand,Name,Price,Rank,Ingredients,Combination,Dry,Normal,Oily,Sensitive
0,Moisturizer,LA MER,Crème de la Mer,175,4.1,"Algae (Seaweed) Extract, Mineral Oil, Petrolat...",1,1,1,1,1

In [16]:
raw.shape

(23, 11)