### Collection-data

In [13]:
import chromadb

client = chromadb.PersistentClient(path="db")
col = client.get_collection(name="cosmetics_kb")

N = 5

# ids include listesine konmaz. ids zaten döner.
data = col.get(include=["documents", "metadatas"], limit=N)

#data.keys()
#data["metadatas"][0]["brand"]
data["documents"][0]
#col.get()

Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given

'Ürün adı: Your Skin But Better™ CC+™ Cream with SPF 50+\nMarka: IT COSMETICS\nKategori: Moisturizer\nFiyat: 38\nPuan: 4.1\nUygun cilt tipleri: Combination, Dry, Normal, Oily, Sensitive\n\nÜrün tanıtımı: Bu ürün, cilt tonunu eşitlemeye yardımcı olan ve yüksek faktörlü güneş koruması sunan bir CC kremdir. Cilt görünümünü iyileştirmeye yönelik çeşitli bileşenler içerebilir.\nİçerik analizi: Ürün, salyangoz salgısı, niasinamid ve peptitler gibi birçok aktif bileşen ile zengin bitki özleri ve yağlar içerir. Stearic Acid, Persea Gratissima (Avocado) Oil gibi içerikler komedojenik risk taşıyabilir. Narenciye yağları (örn. Citrus Medica Limonum (Lemon) Peel Oil), Eucalyptus Globulus Leaf Oil ve Chlorhexidine Digluconate hassasiyet/iritasyon riski yaratabilir. Formül genel olarak nemlendirici ve besleyici özellikler sunmayı hedefler.\n\nIngredients: Water, Snail Secretion Filtrate, Phenyl Trimethicone, Dimethicone, Butylene Glycol, Butylene Glycol Dicaprylate/Dicaprate, Orbignya Oleifera Seed Oil, Butyloctyl Salicylate, Cetyl Peg/Ppg-10/1 Dimethicone, Cyclopentasiloxane, Cyclohexasiloxane, Magnesium Sulfate, Polyglyceryl-4 Isostearate, Dimethicone/Vinyl Dimethicone Crosspolymer, Aluminum Hydroxide, Hexyl Laurate, Stearic Acid, Calcium Stearate, Caprylyl Glycol, Triethoxycaprylylsilane, Ethylhexylglycerin, Citrus Medica Limonum (Lemon) Peel Oil, Tocopheryl Acetate, Sorbitan Isostearate, Phenoxyethanol, Citrus Aurantium Bergamia (Bergamot) Fruit Oil, 1,2-Hexanediol, Disodium Edta, Citrus Aurantium Dulcis (Orange) Peel Oil, Citrus Aurantifolia (Lime) Oil, Vitis Vinifera (Grape) Seed Oil, Punica Granatum Seed Oil, Pinus Sylvestris Leaf Oil, Persea Gratissima (Avocado) Oil, Niacinamide, Citrus Grandis (Grapefruit) Peel Oil, Cholesterol, Anthemis Nobilis Flower Water, Lactobacillus/Honeysuckle Flower/Licorice Root/Morus Alba Root/Pueraria Lobata Root/Schizandra Chinensis Fruit/Scutellaria Baicalensis Root/Sophora Japonica Flower Extract Ferment Filtrate, Perfluorohexane, Olea Europaea (Olive) Leaf Extract, Glycerin, Eucalyptus Globulus Leaf Oil, Camellia Sinensis Leaf Extract, Chrysanthemum Indicum Flower Extract, Pueraria Lobata Root Extract, Perfluorodecalin, Morus Alba Fruit Extract, Magnolia Kobus Bark Extract, Glycine Soja (Soybean) Sprout Extract, Diospyros Kaki Leaf Extract, Cinnamomum Cassia Bark Extract, Artemisia Princeps Leaf Extract, Pentafluoropropane, Curcuma Longa (Turmeric) Root Extract, Steareth-20, Hydrolyzed Hyaluronic Acid, Colloidal Oatmeal, Hydrolyzed Silk, Citric Acid, Sodium Benzoate, Potassium Sorbate, Aloe Barbadensis Leaf Extract, N-Hydroxysuccinimide, Hydrolyzed Collagen, Caprylhydroxamic Acid, Tocopherol, Thiamine Hcl, Riboflavin, Retinyl Palmitate, Pantothenic Acid, Palmitoyl Oligopeptide, Niacin, Folic Acid, Chrysin, Carnitine Hcl, Biotin, Ascorbic Acid, Palmitoyl Tetrapeptide-7, Chlorhexidine Digluconate. May Contain: Iron Oxides (Ci 77492, Ci 77491, Ci 77499).\n'

### Excel

In [14]:
import pandas as pd
raw = pd.read_excel("data/uploads/cosmetics-data1.xlsx")
raw.head()

,Label,Brand,Name,Price,Rank,Ingredients,Combination,Dry,Normal,Oily,Sensitive
0,Moisturizer,LA MER,Crème de la Mer,175,4.1,"Algae (Seaweed) Extract, Mineral Oil, Petrolat...",1,1,1,1,1
1,Moisturizer,SK-II,Facial Treatment Essence,179,4.1,"Galactomyces Ferment Filtrate (Pitera), Butyle...",1,1,1,1,1
2,Moisturizer,DRUNK ELEPHANT,Protini™ Polypeptide Cream,68,4.4,"Water, Dicaprylyl Carbonate, Glycerin, Ceteary...",1,1,1,1,0
3,Moisturizer,LA MER,The Moisturizing Soft Cream,175,3.8,"Algae (Seaweed) Extract, Cyclopentasiloxane, P...",1,1,1,1,1
4,Moisturizer,IT COSMETICS,Your Skin But Better™ CC+™ Cream with SPF 50+,38,4.1,"Water, Snail Secretion Filtrate, Phenyl Trimet...",1,1,1,1,1

In [15]:
raw[raw["Name"] == "Crème de la Mer"]

,Label,Brand,Name,Price,Rank,Ingredients,Combination,Dry,Normal,Oily,Sensitive
0,Moisturizer,LA MER,Crème de la Mer,175,4.1,"Algae (Seaweed) Extract, Mineral Oil, Petrolat...",1,1,1,1,1

In [16]:
raw.shape

(23, 11)